<a href="https://colab.research.google.com/github/ahmed-raza-ai/first-day-of-python-programming/blob/main/second___ml__practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv("/archive (1) (1).zip")
df.head(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished

In [ ]:
df.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [ ]:
df.dtypes

price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object

In [ ]:
df[['price', 'area' ,'bedrooms' , 'bathrooms' ,'prefarea','furnishingstatus', 'stories' , 'basement' ,'hotwaterheating','guestroom', "mainroad"]].isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
prefarea            0
furnishingstatus    0
stories             0
basement            0
hotwaterheating     0
guestroom           0
mainroad            0
dtype: int64

In [ ]:
df['hotwaterheating'] = df['hotwaterheating'].fillna(df['hotwaterheating'].mode()[0])
df['hotwaterheating'].head(13)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    1
12    0
Name: hotwaterheating, dtype: int64

In [ ]:
df['furnishingstatus'] = df['furnishingstatus'].fillna(df['furnishingstatus'].mode()[0])
df['furnishingstatus']

0           furnished
1           furnished
2      semi-furnished
3           furnished
4           furnished
            ...
540       unfurnished
541    semi-furnished
542       unfurnished
543         furnished
544       unfurnished
Name: furnishingstatus, Length: 545, dtype: object

In [ ]:
df['airconditioning'] = df['airconditioning'].fillna(df['airconditioning'].mode()[0])
df['airconditioning']

0      1
1      1
2      0
3      1
4      1
      ..
540    0
541    0
542    0
543    0
544    0
Name: airconditioning, Length: 545, dtype: int64

In [ ]:
df['basement'] = df['basement'].fillna(df['basement'].mode()[0])
df['basement']

0      0
1      0
2      1
3      1
4      1
      ..
540    1
541    0
542    0
543    0
544    0
Name: basement, Length: 545, dtype: int64

In [ ]:
df['mainroad'] = df['mainroad'].fillna(df['mainroad'].mode()[0])
df['mainroad']

0      1
1      1
2      1
3      1
4      1
      ..
540    1
541    0
542    1
543    0
544    1
Name: mainroad, Length: 545, dtype: int64

In [ ]:
df['prefarea'] = df['prefarea'].fillna(df['prefarea'].mode()[0])
df['prefarea']

0      1
1      0
2      1
3      1
4      0
      ..
540    0
541    0
542    0
543    0
544    0
Name: prefarea, Length: 545, dtype: int64

In [ ]:
df['bedrooms'] =df['bedrooms'].fillna(df['bedrooms'].mean())
df['bedrooms']

0      4
1      4
2      3
3      4
4      4
      ..
540    2
541    3
542    2
543    3
544    3
Name: bedrooms, Length: 545, dtype: int64

In [ ]:
df['stories'] =df['stories'].fillna(df['stories'].mean())
df['stories']

0      3
1      4
2      2
3      2
4      2
      ..
540    1
541    1
542    1
543    1
544    2
Name: stories, Length: 545, dtype: int64

In [ ]:
df['bathrooms'] = df['bathrooms'].fillna(df['bathrooms'].mean())
df['bathrooms']

0      0
1      0
2      0
3      0
4      0
      ..
540    0
541    0
542    0
543    0
544    0
Name: bathrooms, Length: 545, dtype: int64

In [ ]:
df['parking'] = df['parking'].fillna(df['parking'].mean())
df['parking']

0      2
1      3
2      2
3      3
4      2
      ..
540    2
541    0
542    0
543    0
544    0
Name: parking, Length: 545, dtype: int64